pep_version: 2.0.0
sample_table: "sample_table.csv"
looper:
  output_dir: "results/pep_demo"
  results_subdir: "bedshifted_regions"
  pipeline_interfaces: ["../piface_similarity_scores.yaml"]
sample_modifiers:
  append:
    pipeline_interfaces: "../piface_bedshift.yaml"
    base_path: "$CODE/bedshift_analysis/data/" # Path to BED files to be perturbed
    universe: "$CODE/bedshift_analysis/data/ALL_1000overlap_300files_segments.bed" # REPLACE with path to universe
    chrom_lens: "refgenie://hg38/fasta.chrom_sizes" # REPLACE with path to chrom_lens file
    repeat: 15
  derive:
    attributes: file
    sources:
      DEMO_FILE: 0f84fea95b736ec99914bc66e74ab6e0.bed
